module.exports={
    routes:[
        {
            method:"POST",
            path:"/content-manager/collection-types/api::video-detail.video-detail",
            handler:"search.search"
        }
    ]
}